# Generated by Django 5.1.1 on 2024-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsapp", "0002_state_delete_pet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("empid", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
